### ISSUE TITLE
Doesn't automatically log in, Chrome

### ISSUE THREAD

**Issue by ZeromusPE** [Alsciende/thronesdb#10]
When I open Chrome, the thronesdb.com page opens to the login screen.  The "Remember me" box is unchecked (even if I previously checked it).  The Username and Password fields are filled.

I've only tested this in Chrome.  netrunnerdb.com logs me in automatically.

**Comment by Alsciende** [comment]
Thank you, I was struggling with this session issue, and your bug ticket opened my eyes :D
