### ISSUE TITLE
Flavor text exclamation point

### ISSUE THREAD

**Issue by mplain** [Alsciende/thronesdb#100]
In the flavor text, the exclamation point is tilted the wrong way.

![1](https://cloud.githubusercontent.com/assets/7605827/19734302/b7f97190-9baf-11e6-87cf-db5fb5df0ce6.png)

![2](https://cloud.githubusercontent.com/assets/7605827/19734303/b800c8aa-9baf-11e6-86f8-fb5b14a283bf.png)

**Comment by Alsciende** [comment]
I can't find a better font on Google Fonts :(

**Comment by mplain** [comment]
Solved?

**Comment by mplain** [comment]
This seems to be fixed.
