### ISSUE TITLE
includes card codes in download/export formats

### ISSUE THREAD

**Issue by zacchiro** [Alsciende/thronesdb#107]
Unless I'm missing something, neither of the currently available export/download formats for decks (plain text/OCTGN) allow to reference cards using their [thronesdb-json-data](https://github.com/Alsciende/thronesdb-json-data), e.g., 04081.

What do you think of adding the code to either of the currently available download formats?

Alternatively, one could think of adding a new download format just for this, e.g., JSON, where all available card info in JSON format are inlined.

With many thanks for ThronesDB!

**Comment by Alsciende** [comment]
I think the best way to do that is to use the API: http://thronesdb.local/app_dev.php/api/doc#get--api-public-decklist-{decklist_id}.{_format}
