### ISSUE TITLE
Deckbuilder validates unique plot limits incorrectly on "Rains of Castamere" agenda

### ISSUE THREAD

**Issue by stopfstedt** [Alsciende/thronesdb#112]
![screencapture-thronesdb-deck-edit-212154-1480494416777](https://cloud.githubusercontent.com/assets/1410427/20745016/0631bd5a-b694-11e6-9cdc-f703f5ed69f9.png)

"Contains more than one duplicated plot" is a false positive.

**Comment by Alsciende** [comment]
Thank you :)
