### ISSUE TITLE
Feature Request: Delta Report

### ISSUE THREAD

**Issue by aufruf** [Alsciende/thronesdb#117]
Hi,

It would be useful to get a report about the changes made since the last save.

Scenario: Updating a deck online and back home need to do the card / sleeve moves...

Many thanks for the great development and time you guys put in this.

Cheers

**Comment by jbrz** [comment]
Is the "History" Tab not what you're looking for, @aufruf

**Comment by aufruf** [comment]
Ha! Yes, it is exactly what I was looking for. Thanks a lot - can be closed / marked as solved :D
