### ISSUE TITLE
Ghosts of Harrenhall incorrectly labelled 'Plot deck limit 1'

### ISSUE THREAD

**Issue by Stephen986** [Alsciende/thronesdb#119]
Ghosts of Harrenal on Thronesdb is written as: Plot. Income: 2. Initiative: 5. Claim: 1. Reserve: 5. Plot deck limit: 1

However nowhere on the card does it say there is a limit of 1 per plot deck.  That text should be changed, and you should be able to add 2 copies in your deck on Thronesdb.

**Comment by mplain** [comment]
Yes yes, I've submitted a fix for this.

**Comment by mplain** [comment]
Fixed.
