### ISSUE TITLE
Filter keyword e (for packs) is broken. eg. e:Black for all cards from Taking the Black

### ISSUE THREAD

**Issue by XGDragon** [Alsciende/thronesdb#122]
It only seems to work for cards from the Core Set. A simple search "e:Core" will work. Searching e:Black returns a HTTP Error 500. 

![image](https://cloud.githubusercontent.com/assets/6887149/22186596/4eb03d84-e0f8-11e6-8d55-9639b81acfee.png)

**Comment by Alsciende** [comment]
"e" excepts the code the pack, not a part of its name. Try "e:TtB" instead.
