### ISSUE TITLE
Cannot import decks from OCTGN files

### ISSUE THREAD

**Issue by mplain** [Alsciende/thronesdb#125]
Importing a deck from an OCTGN file causes an error:
"Cannot import deck without faction"
Even if I just download that same deck from ThronesDB!

**Comment by Alsciende** [comment]
I think this is because the latest pack didn't have octgn ids. I have no issue exporting/importing a decklist from older packs; do you?

**Comment by Alsciende** [comment]
Hmm no there's another problem. I can't import your deck from yesterday.
