### ISSUE TITLE
Unable to save decks

### ISSUE THREAD

**Issue by JalekZem** [Alsciende/thronesdb#126]
I have been using the DB for a few months and had no issues.  Then in the last 2 days, I have been unable to save.  I am using Windows Vista, and Firefox (v 51.0.1) and when I go to save the deck, I get transferred to a blank white page and the deck changes are not saved.  In addition, when I goto history, the changes are there, but they do not get added to the deck.

**Comment by Alsciende** [comment]
Thank you, bug fixed
