### ISSUE TITLE
Error when searching with text filter in deckbuilder

### ISSUE THREAD

**Issue by samuellinde** [Alsciende/thronesdb#128]
When using the text filter (x:) on the deckbuilding page, cards without any text are returned no matter the search term.

<img width="590" alt="screen shot on 2017-02-09 at 20-42-54-2" src="https://cloud.githubusercontent.com/assets/57992/22800198/dec65b38-ef08-11e6-9f62-357eaa9f57e0.png">

**Comment by stopfstedt** [comment]
looks like this already got fixed.
