### ISSUE TITLE
Final Fantasy DB?

### ISSUE THREAD

**Issue by milchteee** [Alsciende/thronesdb#140]
Hey Alsciende! I love all your DBs so far (and happen to play almost all of the games you have DBs for) and was wondering if you have heard of or played Final Fantasy TCG? They recently rebooted the game and I sorely miss an alsciende.db for the game. Would it be difficult to do? Thanks a lot!

**Comment by fafranco82** [comment]
I don't know if Alsciende have time to do it... I don't have a lot either, but if there is some place with a lot of  resources about FF TCG (rules, card images, etc.) I can try to build one, at least something minimal, and then someone continue with the work.

For reference, I adapted de 'alsciende.db' code for Star Wars  Destiny (swdestinydb.com), and also I18Nd thronesdb.

**Comment by milchteee** [comment]
Nice! There are existing sites actually, like fftcgmognet.com and fftcgdb.com. The former is more up-to-date wrt images.

**Comment by milchteee** [comment]
Hey fafranco82! Any updates on the situation?

**Comment by stopfstedt** [comment]
hey @milchteee - just going through old tickets. a final fantasy deckbuilder is not on the horizon, sorry. that being said - the code for thronesdb is open source, anyone is free to fork it and build their own deckbuilder. it would require some coding skills to do so, but the option exists.
