### ISSUE TITLE
[bug] Four cards match any filter by card text

### ISSUE THREAD

**Issue by EricWarnke** [Alsciende/thronesdb#141]
Filtering by card text seems to always bring up the following cards, regardless of what you set x to:

- Courtesan of the Rose
- House Dayne Knight
- House Maester
- The Winds of Winter

![image](https://cloud.githubusercontent.com/assets/1396469/24718749/5bf3d296-19f4-11e7-931c-872c58a45b0a.png)

**Comment by stopfstedt** [comment]
duplicated in #156 and #152
