### ISSUE TITLE
Enhancement request:  When viewing a decklist, only show expansions that have cards in the decklist

### ISSUE THREAD

**Issue by benyar** [Alsciende/thronesdb#147]
When I build, I always select to have all expansions available to me, mostly because I don't remember what goes where.  That translates directly over to viewing published decklists.  If viewing a published decklist only shows the expansions used in building the deck (instead of the expansions that the deck author chose from, which is generally all of them), it would greatly aid new players in deciding on which packs to get immediately... instead of thinking they have to get all 14+ expansions, 3 big box sets, and 3 core sets to start enjoying the game.

**Comment by Alsciende** [comment]
Do you have an example of a decklist that, when viewed, doesn't show only the expansions used in that decklist?

**Comment by benyar** [comment]
No.  I guess I didn't realize that was a thing already, nor did I realize I
was building decks from so many packs.  My apologies for not looking
closely.

**Comment by Alsciende** [comment]
No worries :)
