### ISSUE TITLE
Images for The Nightfort and Holding the Trident

### ISSUE THREAD

**Issue by ystros** [Alsciende/thronesdb#150]
I'm not 100% sure this is the appropriate place to raise this, as it's not clear how card images are managed for the site.

I've scanned copies of both The Nightfort and Holding the Trident from the Valyrian Draft Set, which are currently missing images on the site.

Apologies for the relatively low quality, as I don't own a scanner and had to go to a office center which had a kinda low-end one.
Holding the Trident - https://i.imgur.com/XGiyswW.png
The Nightfort - https://i.imgur.com/UiYsp0f.png

**Comment by mplain** [comment]
Could you please provide raw scans? 150 dpi would be nice. I'll edit them myself. These are unevenly cut.

**Comment by ystros** [comment]
Here were the raw scans I took that day - unfortunately it's the same resolution, but you can probably cut it better than I did:
https://i.imgur.com/l4oNdvl.png
https://i.imgur.com/6W8koaT.png

If it's helpful I can go back to the place I scanned them and see if it's possible to scan at a higher resolution (or find somewhere else to scan them). It just may be a few days before I'm able to get around to it.

**Comment by mplain** [comment]
I don't want to seem to picky, but... If you have a possibility to go back and scan them again, at 150 dpi and without the scanner cutting the corners (it does that because you put the card in the corner of the scanner, don't worry about it not being positioned straight, I can rotate it later), I'd really appreciate it if you could scan them once more. I can wait a week or two or however long it takes. Thank you!!

**Comment by Alsciende** [comment]
We can work with these images, but I agree with @mplain that it would be better if you can manage to share scans with a higher dpi and the cards away from the corner. Thank you Brian!

**Comment by ystros** [comment]
Not picky at all! Will see if I can get better scans, probably sometime later this week.

**Comment by ystros** [comment]
Here are some updated raw scans. I did at two qualities - 150dpi as requested and 300dpi in case that's helpful. Click the 'Download' button in the upper right to get the full files instead of the scaled-down preview it shows on the Dropbox website itself.

150dpi (10MB) - https://www.dropbox.com/s/yd8beze85df7jhc/draft-cards-150dpi2.png?dl=0
300dpi (50MB) - https://www.dropbox.com/s/js36jc33q0ekr1l/draft-cards-300dpi2.png?dl=0

Let me know if you need other adjustments / higher quality!

**Comment by mplain** [comment]
Thanks! On it!

**Comment by ystros** [comment]
These appear to have been added to the site now, closing this issue. Thanks!

**Comment by mplain** [comment]
Thank YOU!
