### ISSUE TITLE
House Maester and Courtesan of the Rose ≠ Stealth

### ISSUE THREAD

**Issue by POnofre** [Alsciende/thronesdb#156]
Every time I search "x:stealth", these two pop up. They clearly don't have stealth. So... this should probably get fixed, please.

**Comment by mplain** [comment]
Same as #152

**Comment by stopfstedt** [comment]
seems to have been fixed: http://thronesdb.com/find?q=x%3Astealth&sort=name&view=list

**Comment by Alsciende** [comment]
Closed as duplicate
