### ISSUE TITLE
new API endpoint - Fetch card by name

### ISSUE THREAD

**Issue by DimitrisNL** [Alsciende/thronesdb#158]
I'd like to make a small bot, which will returns the details of a requested card.
I would be great to have a new endpoint where :

- If I ask for 'moon boy', I'll get the the following JSON (https://thronesdb.com/api/public/card/02047)

- If I query for 'moon b', there's no exact match - so don't bother with it at all 404

- When it's a card with multiple versions, an array of them would be returned.

I intend to use it in the discord channel of my meta, and maybe introduce it to the general AGOT one when it's ready.

**Comment by Alsciende** [comment]
I understand the appeal, but it's not possible. I'm encouraging you to query the whole data, put it in cache, and make your own search engine. You can see a similar bot for l5r here: https://github.com/MyrionPhoenixmoon/l5r-discord-bot
