### ISSUE TITLE
(maybe) Misprinted Journey to Oldtown CP Code?

### ISSUE THREAD

**Issue by Grugn0** [Alsciende/thronesdb#162]
For Chapter Pack: "Journey to Oldtown" the code is JoO, maybe it shoud have been JtO?

**Comment by mplain** [comment]
Thank you!!

**Comment by mplain** [comment]
Fixed.

**Comment by Shivan0910** [comment]
Hello,
there is 2 Journey to Oldtown packs in the packs listing... One JoT, the other one is JoO.

**Comment by fafranco82** [comment]
@Alsciende You are the only one that can delete the pack with code 'JoO' from the database :)

**Comment by Alsciende** [comment]
Done
