### ISSUE TITLE
installation via composer fails on Linux

### ISSUE THREAD

**Issue by stopfstedt** [Alsciende/thronesdb#177]
Hi there,
just attempted a fresh installation of thronesdb on my local machine (Ubuntu 16), and it failed in the post-installation phase with this error:

```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                                                                             
  Unable to parse file "/home/stefan/dev/projects/thronesdb/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/../Resources/config/web.xml".  
```

You can see the full output in this [gist](https://gist.github.com/stopfstedt/bf1619a2199568561cde90fc685b6d69).

I traced this issue back to a composer issue with the SensionDistributionBundle, a [proposed solution is to upgrade that dependency](https://github.com/composer/composer/issues/6203#issuecomment-314179326).

Will put a PR with a fix in momentarily.

**Comment by Alsciende** [comment]
I just did a fresh install too, and got no problem. What is your php version?

**Comment by Alsciende** [comment]
I updated the vendors, let me know if your problem is fixed.

**Comment by stopfstedt** [comment]
i'm running PHP 7.2 on Ubuntu 16.04. recent composer version.
```
$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

$ php -v
PHP 7.2.0-2+ubuntu16.04.1+deb.sury.org+2 (cli) (built: Dec  7 2017 20:14:31) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0-2+ubuntu16.04.1+deb.sury.org+2, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.6.0beta1, Copyright (c) 2002-2017, by Derick Rethans

$ composer --version
Composer version 1.6.2 2018-01-05 15:28:41
```

from what [i've been reading](https://github.com/composer/composer/issues/6203#issuecomment-314179326), the issue is with newer composer builds and older symfony versions.
what's your composer version?

anyhow, i'll give it a go again with the updated dependencies tonight and provide feedback here.

_sidenote:_ any plans on going up to Symfony 3 this year? let me know if so, i'd be happy to help.

**Comment by Alsciende** [comment]
```
$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

$ php -v
PHP 7.1.12-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Dec 14 2017 15:37:13) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12-3+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies

$ composer --version
Composer version 1.5.5 2017-12-01 14:42:57
```

**Comment by Alsciende** [comment]
I updated to composer 1.6.2 and re-run `composer install`. It all went well.

**Comment by Alsciende** [comment]
I'd love to upgrade to Symfony 3.4 and php 7. I did it for netrunnerdb already, it's a matter of a few hours. If you want to do it, I'll be happy to upgrade the server :)

**Comment by Alsciende** [comment]
Even better, I'd like to improve a few areas of the app, like the importer (migrating to https://github.com/Alsciende/serializer-bundle) and the queries (moving everything to ORM, Query Builder and Repositories).

**Comment by stopfstedt** [comment]
thanks for the feedback. 
i just tried this again and no dice, still. then, i went back to previous composer versions, and 1.2.4 is the most recent one that works for me. this confirms what other people were reporting in that thread that i linked to earlier. so it must be Linux (or perhaps Ubuntu-specific) issue.

re: upgrading to Symfony3 - i'll take a stab at it next month. shouldn't be a big deal. will check out the serializer bundle while at it.

**Comment by Alsciende** [comment]
How strange. Can you copy the content of your `vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/web.xml` file? Mine is

```xml
<?xml version="1.0" ?>

<container xmlns="http://symfony.com/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <parameters>
        <parameter key="controller_resolver.class">Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver</parameter>
        <parameter key="controller_name_converter.class">Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser</parameter>
        <parameter key="response_listener.class">Symfony\Component\HttpKernel\EventListener\ResponseListener</parameter>
        <parameter key="streamed_response_listener.class">Symfony\Component\HttpKernel\EventListener\StreamedResponseListener</parameter>
        <parameter key="locale_listener.class">Symfony\Component\HttpKernel\EventListener\LocaleListener</parameter>
    </parameters>

    <services>
        <service id="controller_name_converter" class="%controller_name_converter.class%" public="false">
            <tag name="monolog.logger" channel="request" />
            <argument type="service" id="kernel" />
        </service>

        <service id="controller_resolver" class="%controller_resolver.class%" public="false">
            <tag name="monolog.logger" channel="request" />
            <argument type="service" id="service_container" />
            <argument type="service" id="controller_name_converter" />
            <argument type="service" id="logger" on-invalid="ignore" />
        </service>

        <service id="response_listener" class="%response_listener.class%">
            <tag name="kernel.event_subscriber" />
            <argument>%kernel.charset%</argument>
        </service>

        <service id="streamed_response_listener" class="%streamed_response_listener.class%">
            <tag name="kernel.event_subscriber" />
        </service>

        <service id="locale_listener" class="%locale_listener.class%">
            <tag name="kernel.event_subscriber" />
            <argument type="service" id="request_stack" />
            <argument>%kernel.default_locale%</argument>
            <argument type="service" id="router" on-invalid="ignore" />
        </service>

        <service id="translator_listener" class="Symfony\Component\HttpKernel\EventListener\TranslatorListener">
            <argument type="service" id="translator" />
            <argument type="service" id="request_stack" />
            <tag name="kernel.event_subscriber" />
        </service>

        <service id="validate_request_listener" class="Symfony\Component\HttpKernel\EventListener\ValidateRequestListener">
            <tag name="kernel.event_subscriber" />
        </service>
    </services>
</container>

```

**Comment by Alsciende** [comment]
So just to be sure, if you run `composer install --no-scripts`, there is no error? But if you run `php app/console` or `php app/console cache:clear`, there is an error?

**Comment by Alsciende** [comment]
Also, what is your version of the xml lib?

```
$ xml2-config --version
2.9.4
```

**Comment by stopfstedt** [comment]
@Alsciende thanks for the suggestions above.

1. running `composer install --no-scripts` succeeds, as expected. the failure is in the post-install script processing. running `php app/console` fails, also expected (incompete install).

2. my `xml2-config` version is the same as yours.

3. i diffed your `web.xml` against mine, it's the same.

for posterity, i dumped my terminal output into this [gist](https://gist.github.com/stopfstedt/e309caec01b8c978651bc989ffd37350)

anyhow, i think i'm hitting a wall here, and it's not worth further investigating (considering we'll upgrade out of this situation soon). 
the workaround is to downgrade composer as needed, this will do in the mean time.

thanks again for checking into this!
