### ISSUE TITLE
API part of the website returns 500 HTTP error 

### ISSUE THREAD

**Issue by luky92** [Alsciende/thronesdb#184]
As the title says the api part is broken atm

**Comment by Alsciende** [comment]
Which endpoint returns a 500?

**Comment by luky92** [comment]
API doc link at the botom of the website

**Comment by luky92** [comment]
![image](https://user-images.githubusercontent.com/15126111/36342164-70a3206a-13fa-11e8-8c0e-d8bb7d648a5e.png)
this here :) maybe i should have uploded it erlier :)

**Comment by Alsciende** [comment]
Ok, I'll look into it shortly :)

**Comment by Alsciende** [comment]
Fixed
