### ISSUE TITLE
missing images for FotOG chapter pack

### ISSUE THREAD

**Issue by zacchiro** [Alsciende/thronesdb#186]
As per topic, the chapter pack is here https://thronesdb.com/set/FotOG/card , with all card details, but images are missing. The chapter has been officially released and all scans are available from cardgamedb http://www.cardgamedb.com/index.php/agameofthrones2ndedition/a-game-of-thrones-2nd-edition-cards/_/flight-of-crows-cycle/favor-of-the-old-gods/

**Comment by Alsciende** [comment]
Thanks.
