### ISSUE TITLE
Not showing Core set cards

### ISSUE THREAD

**Issue by josefsallen** [Alsciende/thronesdb#19]
I have "core set" and Taking the Black checked, and it should be allowing 3 core sets. Instead, it's only showing the cards from Taking the Black. I've tried closing out and reopening, messed with the check boxes, etc.

**Comment by Alsciende** [comment]
Holy cow, I was a bit reckless when I changed "core" for "Core" as the code for the Core Set. I reverted back to "core", things should be back to normal

**Comment by josefsallen** [comment]
Thanks! It's an awesome implementation!
