### ISSUE TITLE
validate decks that use The Wars To Come agenda

### ISSUE THREAD

**Issue by zacchiro** [Alsciende/thronesdb#195]
Related to #192 , which is merged but (I guess) not deployed.

**Comment by Alsciende** [comment]
@zacchiro It should be deployed now.

**Comment by zacchiro** [comment]
On Wed, May 02, 2018 at 09:56:37AM +0000, Cédric Bertolini wrote:
> @zacchiro It should be deployed now.

thanks! I confirm it works now :-)
