### ISSUE TITLE
Feature Request: "My decks" show agend pictures

### ISSUE THREAD

**Issue by alexmonk** [Alsciende/thronesdb#2]
In netrunner there are many identities (but only 7 factions), and in netrunnerdb it is easy to search "my decks" simply by looking on pictures.
In Game of Thrones there are 8 factions - and looking on pictures on this factions in "my decks" do not helps to navigate through decks.
My request - add picture of agenda next to faction picture - it will ease navigation.

**Comment by alexmonk** [comment]
Maybe add this feature to decklists search?

**Comment by Alsciende** [comment]
Decklists also display the 2 images.
