### ISSUE TITLE
update Rules Reference to describe shadow

### ISSUE THREAD

**Issue by zacchiro** [Alsciende/thronesdb#203]
Together with The Shadow City chapter pack, we got a rule update describing the shadow mechanic. It should be added to the Rules Reference page.

**Comment by mplain** [comment]
It was added and merged, now it needs to be deployed.

**Comment by mplain** [comment]
Aaand deployed :)

**Comment by zacchiro** [comment]
On Wed, Jun 20, 2018 at 11:44:02AM +0000, mplain wrote:
> Aaand deployed :)

thanks! :)
