### ISSUE TITLE
Not getting the reg. email. 

### ISSUE THREAD

**Issue by EskiMoses** [Alsciende/thronesdb#205]
Tried making two different accounts with two different emails. But I never recieve the reg. email on either of them. And when i press "Never got the registration email?" nothing happens :(

Please help :)

Best regards,
Adrian from Denmark.

**Comment by dcjoker** [comment]
Same problem.

**Comment by BokkieDoke** [comment]
It's not working for me either. I tried multiple emails and also tried resending the registration emails.

**Comment by Alsciende** [comment]
@EskiMoses @dcjoker @BokkieDoke your accounts should be activated now
