### ISSUE TITLE
text file import unable to handle variants of same-titled cards

### ISSUE THREAD

**Issue by stopfstedt** [Alsciende/thronesdb#218]
follow-up item to #215 

if you upload a list that contains a titled card that has multiple versions (e.g. "Arya Stark", "The Red Viper" etc.), the given expansion information is discarded. This can result in the wrong version being imported. 

Example: [Arya Stark](https://thronesdb.com/card/08081) from the "The Faith Militant" chapter pack is to be imported.  
The line item on the import text file looks like:
`1x Arya Stark (The Faith Militant)`

However, [Core Arya](https://thronesdb.com/card/01141) is imported, incorrectly.

The problem is the regular expression in the DeckImportService ignoring the expanion's name, as specified in parenthesis after the card's title. The fix needs to be applied there.

**Comment by stopfstedt** [comment]
I'd be happy to take a stab at this, after #217 get's merged, since I'm already in that head space.

**Comment by stopfstedt** [comment]
refs #https://github.com/Alsciende/thronesdb/issues/61#issuecomment-275627067

**Comment by alessandro-guagnelli** [comment]
This is another bug I also found, and I was also going to look into this. Thing is, I am not that proficient with git, and I couldn't take a look for a fix. I believe that the issue is that the DeckImportService uses findOneBy, which only returns the first result.

**Comment by stopfstedt** [comment]
i decided to roll this fix in with the other one. 

@alessandro-guagnelli - git (and github) supports branching, you can have multiple code branches of the same code base, it helps separating out features, bugs etc into smaller, more digestible change sets. check it out: https://help.github.com/articles/about-branches/

**Comment by alessandro-guagnelli** [comment]
> @alessandro-guagnelli - git (and github) supports branching, you can have multiple code branches of the same code base, it helps separating out features, bugs etc into smaller, more digestible change sets. check it out: https://help.github.com/articles/about-branches/

Hi stopfstedt! Thanks for pointing me out to some resource. I know that git is a powerful tool, the point is that right now I've only been using it as a versioning tool, and just a couple of time on the same repo with someone else, so I lack the basis to use it. Let's say that I can easily git pull, push and commit, the other commands are still something dark. 

For example, even thou I had just to edit that single file, I'd still be asking, should I start from my own head, or open another for the fix? I guess it's the latter, but again, how do I manage branches? I believe it's easy enough, but I still didn't have the time to look into that. I prefer to take things easy for the moment, one pull at the time, until I manage to get a better look at git 😄 I hope I'll have some time in the next few days.
