### ISSUE TITLE
not receiving password reset email

### ISSUE THREAD

**Issue by stopfstedt** [Alsciende/thronesdb#219]
tried to reset password last night, and haven't received an email with a reset link 24hr later.

had the same issue come up from other users in a FB thread earlier this week, hereby confirming.

please fix, thanks!

**Comment by Alsciende** [comment]
Hi! ThronesDB cannot send emails anymore. They were mostly rejected by email servers. To restore the functionality, an external SMTP service would need to be configured.

**Comment by stopfstedt** [comment]
hey, thanks for the quick feedback. so getting a proper smtp service rigged up - is this primarily a financial issue? swiftmailer should be configurable rather easily to work with pretty much any provider..

**Comment by Alsciende** [comment]
It's not a financial issue. I got fed up with all the email issues (the server used to send its own emails), and I just removed emails altogether...

**Comment by alessandro-guagnelli** [comment]
Hi @Alsciende, just dropping a couple of thoughts here. Maybe the spf policy was to restrictive? Maybe a `~all ` instead that `-all` could help pinpoint the issue. I see that only mail.thronesdb.com was authorized by spf to send email from thronesdb.com, which is 46.101.97.239 itself.

I don't have any thronesdb email that I can inspect, but I'd be glad to help on this one

**Comment by stopfstedt** [comment]
Got outbound email to work again. Still waiting on some more feedback before I close this ticket out, but it's looking promising.

**Comment by stopfstedt** [comment]
got a few more confirmations that this is working. _done_.
