### ISSUE TITLE
Import images for Kings of the Isles box

### ISSUE THREAD

**Issue by ystros** [Alsciende/thronesdb#238]
Images are now online at CardgameDB for the Kings of the Isles box, it should be possible (when you get the chance) to run the `app:import:images` command to have them displayed on ThronesDB.

As a future improvement, it might be possible to get rid of this command, as all it does is set the image URL property to FFG's CDN for the image - it used to download and rehost the image. So right now the main value the command is providing is allowing the site to distinguish whether the image has been uploaded by FFG, allowing display of a "No image" message instead of a broken `img` element.

**Comment by stopfstedt** [comment]
thanks for the heads up, i just ran the image importer command. KotI images are up in prod.
