### ISSUE TITLE
Win Loss tracker

### ISSUE THREAD

**Issue by Everr** [Alsciende/thronesdb#27]
Would be very useful if you could keep track of a deck's win/loss rate (by version and for deck in general).
Additionally, being able to pick the type of deck you played against if it's on Thrones, otherwise, just select deck type

**Comment by stopfstedt** [comment]
interesting idea, but not something that's going to make it into thronesdb, at least not any time soon. 

instead, may i suggest you check out https://agotstats.com/, this seems to offer at least some of what you're looking for.
