### ISSUE TITLE
add values to tournament placement drop down in publishing page

### ISSUE THREAD

**Issue by brittfitch** [Alsciende/thronesdb#30]
There is a drop down for 'finished high in tournament' but the values are only: 
2015 winter 
2015 other

potentially add values for SC, regionals, nationals, worlds.
potentially add current year or remove year entirely.

cheers

**Comment by Alsciende** [comment]
I added "2016 Spring", which is only now debuting. I'll add the other 2016 values (Regional, then National) when they are announced by FFG.

**Comment by Alsciende** [comment]
I thought "2015 Winter" and "2016 Spring" were Store Championships, but I now understand they're actually GNK.

I added an option "2016 Store Championship".
