### ISSUE TITLE
Auto-completing a card hash-reference using tab causes the text-cursor to jump to the end of the text entry area

### ISSUE THREAD

**Issue by DominicBisset** [Alsciende/thronesdb#32]
Its annoying to be editing a paragraph and repeatedly having to relocate the cursor to continue typing after the inserted card reference.

**Comment by Alsciende** [comment]
I tried using the keyboard (arrow+enter) and the mouse (click the card name) to insert a card reference, in the deck edit page, in the decklist publish page, in the decklist comment page, and the cursor focus always returns to the text area after the card reference insertion. Using Chrome.

Could you give me more details?

**Comment by Alsciende** [comment]
I think I get it, you are using the "card" button in the toolbar. As a side note, you can also type '#' to include a card reference.
