### ISSUE TITLE
The preview provided by the markdown editor for the published deck description does not match reality

### ISSUE THREAD

**Issue by DominicBisset** [Alsciende/thronesdb#33]
The preview correctly renders bullet points but the description as listed on the published deck page does not.
[See my deck here for example.](http://thronesdb.com/decklist/view/2547/tabletop-games-chester-uk-winter-championship-melee-winner-1.0)  Each list of opponents should be a unordered list, and the preview correctly renders them as such, but the description displays each point inline with the dash that is used to mark down the list.

**Comment by Alsciende** [comment]
As a side note, the markdown converter on the server expects a blank line before every list. That's why your description doesn't display lists.
