### ISSUE TITLE
Track owned Core Sets / Chapter Packs / Deluxe Sets against card use in My Decks

### ISSUE THREAD

**Issue by nilblank** [Alsciende/thronesdb#37]
To help track what cards are set off into our various real world decks, it would be great if we could list the number of Core Sets / Chapter Packs / Deluxe Sets we own, and where those cards are allocated across the deck in My Decks (you'd be able to toggle 'exclude' on decks you don't have built real world). 

This would be immensely helpful for last minute card swaps and collection management.

**Comment by Alsciende** [comment]
I won't include a collection management feature, sorry.
