### ISSUE TITLE
Text deck import is not working

### ISSUE THREAD

**Issue by Sydtrack** [Alsciende/thronesdb#38]
There is a problem while parsing text decks in ThronesDB.

The `app.ui.on_content_change` function inside _deckimport_ is working fine, but the call to `app.deck.init` is broken.

Since `deck.on_data_loaded` is defined in `app.deck.init` to run only after an 'data.app' event is triggered, the deck is never loaded after parsing. Also, calling `deck.init` at every change to the textarea will bind the `$(document).on('data.app', deck.on_data_loaded);` line multiple times (since jQuery 1.4).

**Comment by AlbertoWagner** [comment]
Another problem that will arrive shortly is how to handle homonymous cards.
