### ISSUE TITLE
Add in a chart or statistic displaying percentage of "set-upable" cards

### ISSUE THREAD

**Issue by jamespdaily** [Alsciende/thronesdb#39]
Maybe a miniature version of this: http://agotsetup.com/ added in with the charts and status would be really cool in understanding how well your deck would set up with the deck list you've created

**Comment by jbrz** [comment]
agotsetup is not a simple set of code - a "miniature" version is not a small implementation.  While I don't doubt Alsciende's abilities, I think it just makes more sense to use agotsetup, no?

**Comment by Alsciende** [comment]
I totally agree. If possible, i could put a link to agotsetup.com with the deck as a parameter.

**Comment by jbrz** [comment]
Could see if @jwentworth has a functional way to embed agotsetup or if we can come up with an implementation to import/export directly to/from gotsetup/thronesdb...

**Comment by jwentworth** [comment]
I am working on tighter integration with thronesdb api on the agotsetup side. Once that is done I'm planning on thinking about what an "embeddable" version would look like, which could then be embedded into thronesdb. That was my initial plan/idea on integrating the two anyway
