### ISSUE TITLE
Deck Test draws

### ISSUE THREAD

**Issue by braxton462** [Alsciende/thronesdb#46]
When I run a test draw for my decks, the cards are appearing, at times, spaced out with blank card spots.  Essentially, the cards aren't setting up next to each other.  Is this a broad issue or is it just me?

Thanks for your time!

**Comment by jbrz** [comment]
It's not just you.

My guess is it has something to do with the tables.

Could maybe rework that half of the page with just CSS (flex stuff is fun and class-able)/bootstrap

**Comment by SantiagoPozo** [comment]
Hello!

Great job! Beautiful page! Very professional!

I have the same problem and a couple of suggestions.

Please, add "draw 3" and "draw 4" button. Maybe even the five one. Easy and very functional. 

I use a lot the card draw simulator and i'd like to have it in a empty page in single column or hide the rest of elements while using. It would be great to have a money counter and even to be able of  moving the cards. The last suggestion is quite ambitious, I know. 

Sorry for my English.
Congrats for the page!

**Comment by SantiagoPozo** [comment]
Another: 3 levels of opacity or better, something that indicate the card was removed from game or kelt, a cross over corner's card. 
first click: opacity 0.5 (for me means the card is in the game area)
second click: cross on the corner (for me means the card has been removed from the game area)
... maybe more?...

thank you anyway 

(by the way, my nick in deckbuilder is biliflasca).

**Comment by jbrz** [comment]
@SantiagoPozo you're getting well away from `deckbuilder` features and more towards `simulation` features.  TDB isn't a simulation of a game, it's a tool to build decks.  I think to start entertaining requests like that, Thronesdb would have to drastically change scope.  What would be ideal is a group of developers capable and willing to produce a product for thrones that is like http://jinteki.net - netrunner community-built with support from/for netrunnerDB.  So if that's the level of interaction you want to have, I'd suggest looking for/pushing for an effort such as that

**Comment by SantiagoPozo** [comment]
Thank you. I understand. You are right. Forget everything but...
If you could add the "draw 3" and "draw 4" button I would be so grateful. Most of the times after the imaginary set up, the user draw 3 or 4 cards. Sometimes, 5 cards.

Thank you anyway for your time.

**Comment by Alsciende** [comment]
It's easier to provide the draws that are defined by the game mechanics, "draw 1", "draw 2" and "draw 7". If you want to draw 3, I think it's actually easier to click 3 times on "draw 1", and get used to click on "draw 1" whenever to want to refill your hand. Otherwise, the only good alternative is to add draw 3, 4, 5 and 6, and then the UI loses all simplicity.
