### ISSUE TITLE
octgn corrupt file

### ISSUE THREAD

**Issue by SantiagoPozo** [Alsciende/thronesdb#50]
Hello, 

Sometimes the downloaded octgn file is corrupt. If is corrupt once is always from then on. 

It seems to have a relation with changes on a deck.

Great job!
Biliflasca

A example

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<deck game="30c200c9-6c98-49a4-a293-106c06295c05" sleeveid="0">
  <section name="Faction" shared="False">
    <card qty="1" id="fc822b99-e4df-49f4-beb2-a0e082f224bf">House Targaryen</card>
  </section>
  <section name="Agenda" shared="False">
    <card qty="1" id="f1841168-04de-4aa3-a2f0-8d3b1b8047b2">The Lord of the Crossing</card>
  </section>
  <section name="Plots" shared="False">
    <card qty="1" id="3a3577a4-5ee1-4e9f-a674-49e9f9e81568">Calling the Banners</card>
    <card qty="1" id="4ee52602-89fa-4048-accc-dffdb78bee69">Calm Over Westeros</card>
    <card qty="1" id="ac8effb7-76cb-42e4-ab33-d88a407c0dda">Filthy Accusations</card>
    <card qty="1" id="79877d2a-5b23-4c16-86df-9453c065835b">Fortified Position</card>
    <card qty="1" id="bc3547ae-82fc-4da1-a375-209ba0c07748">Trading with the Pentoshi</card>
    <card qty="2" id="29f2ef9a-c8e6-46e6-86b6-f0c9440804a6">A Song of Summer</card>
  </section>
  <section name="Characters" shared="False">
    <card qty="1" id="499ed82d-cc0e-43a5-89ba-a748b388f528">Littlefinger</card>
    <card qty="1" id="be9304f2-bb5d-4d19-8fbe-4efb6ee24f29">Rattleshirt&#039;s Raiders</card>
    <card qty="2" id="21dda206-536e-4944-8158-b3d174e2b872">Wildling Horde</card>
    <card qty="3" id="a2f21413-0272-47dc-a197-e364aa942d4c">Daenerys Targaryen</card>
    <card qty="2" id="46679e36-a9ce-4e35-ab32-41a6bb88e266">Drogon</card>
    <card qty="2" id="09903f79-6155-4a63-9b52-e10fb2e69898">Khal Drogo</card>
    <card qty="2" id="f5f343ea-a561-415b-adfd-9afdd65820c2">Magister Illyrio</card>
    <card qty="3" id="ac263d0d-d7db-49e7-bdc4-2e131d95aad4">Rhaegal</card>
    <card qty="2" id="1de2665b-53be-4e48-8c5c-42f93fdf40a3">Ser Jorah Mormont</card>
    <card qty="2" id="4819b269-173d-4335-8248-99f0cb4b80a2">Viserion</card>
    <card qty="1" id="6580b898-de89-4a6d-89b4-72cfc3b505e6">Viserys Targaryen</card>
    <card qty="3" id="7177a6da-3afb-4218-be7e-4ca9c03c2157">Braided Warrior</card>
    <card qty="2" id="a575226f-fba6-4d79-bdf7-e5a0c2e0d192">Handmaiden</card>
    <card qty="2" id="0e2c6c02-c6c7-4273-825f-1d03b24998a2">Targaryen Loyalist</card>
    <card qty="2" id="c8012b39-41e9-4276-a83d-149206ea958a">Unsullied</card>
    <card qty="2" id="b9356c1e-a2ac-42fc-855e-3919847a6eda">Crone of Vaes Dothrak</card>
    <card qty="2" id="b785b7fc-2a11-4ba5-87e7-7c06c79d6210">Dothraki Outriders</card>
    <card qty="2" id="d0da5ad5-bd09-4c0f-bbd5-63cda368d6b7">Aggo</card>
  </section>
  <section name="Locations" shared="False">
    <card qty="3" id="90452d99-6a6f-4d0d-b3a1-bb92e7110d1d">The Kingsroad</card>
    <card qty="1" id="51a3e04f-3f44-4417-8d7c-1f116acd5c80">The Roseroad</card>
    <card qty="3" id="bc9a511e-9f90-4b4f-892e-e8ad46103da9">Illyrio&#039;s Estate</card>
    <card qty="2" id="2b59240f-987c-4fc5-b527-35f8d5850beb">Shadowblack Lane</card>
    <card qty="1" id="">Tourney Grounds</card>
  </section>
  <section name="Attachments" shared="False">
    <card qty="1" id="f5173e6f-1ec3-4ee0-8274-755160c57c0e">Bodyguard</card>
    <card qty="1" id="a8bebc54-d01c-424d-8839-460ec09b733f">Milk of the Poppy</card>
    <card qty="1" id="99a12a9c-6e83-43bd-8947-0cc47ffcd02a">Drogo&#039;s Arakh</card>
    <card qty="1" id="b52c7e34-d951-45e5-b296-ade69192855c">Crown of Gold</card>
  </section>
  <section name="Events" shared="False">
    <card qty="2" id="38dd5d15-7214-4c68-9cc4-0d2abd1b2140">Put to the Sword</card>
    <card qty="2" id="b29c7bb5-7b84-4e94-a30b-8332fad51c2a">Tears of Lys</card>
    <card qty="2" id="c5d78fb6-ff52-4012-ac95-547ed9feec0f">The Hand&#039;s Judgment</card>
    <card qty="2" id="aae782b7-cd97-4818-b56a-d1dafe6f80de">Dracarys!</card>
    <card qty="2" id="06a715e0-f26c-4894-8610-63353d73e0fd">Fire and Blood</card>
  </section>
<notes><![CDATA[]]></notes>
</deck>

**Comment by SantiagoPozo** [comment]
ops, the o8d text has been interpreted...
[targ-crossing-big-money.zip](https://github.com/Alsciende/thronesdb/files/233653/targ-crossing-big-money.zip)

**Comment by Alsciende** [comment]
Can you explain what you mean by "the file is corrupt"?

**Comment by Alsciende** [comment]
Oh, I know. It's because Tourney Ground doesn't have a guid.

**Comment by Alsciende** [comment]
Exporting a deck with cards from the War Cycle doesn't work. Those cards are not supported by octgn yet.
