### ISSUE TITLE
 Street of the Sisters

### ISSUE THREAD

**Issue by alexmonk** [Alsciende/thronesdb#54]
Search for "King’s Landing" (https://thronesdb.com/find?q=k%3A%22King%E2%80%99s+Landing%22&sort=faction&view=scan) do not have Street of the Sisters (https://thronesdb.com/card/02018)

**Comment by Alsciende** [comment]
Try https://thronesdb.com/find?q=k%3A%22King%27s+Landing%22&sort=faction&view=spoiler
