### ISSUE TITLE
Text search catches substrings in words

### ISSUE THREAD

**Issue by AdamDziuk** [Alsciende/thronesdb#58]
Searching x:king returns below and  calm over westeros. This seems to be because "attacking" contains "king"

**Comment by Alsciende** [comment]
That seems fine with me. With this behavior, some queries are possible, like "defend", which will match both "defending" and "defender". More importantly, "watch" will match "[thenightswatch]" and "targ" will match "[targaryen]".

**Comment by AdamDziuk** [comment]
Makes sense, but then maybe adding support for escaped spaces?  I wanna find a reason to put a Crown of Gold on Viserys :P

**Comment by Sydtrack** [comment]
Try `x:"<i>king"` to search for keywords inside text

Every keyword is internally written as <b><i>King</i></b>

Also `x:"Attached Character"` works to display multiple spaced strings

**Comment by Alsciende** [comment]
Actually, traits in text are surrounded by `<i>`, not `<b><i>`.

**Comment by Alsciende** [comment]
(it's the css that make them appear bold)

**Comment by Alsciende** [comment]
What if the search on traits (`k`) searched in the card text also?

`k:king`  would do the same as `k:king` and `x:"<i>king</i>"` combined.

**Comment by Sydtrack** [comment]
IMO they should be 2 different prefixes. That way you can search for Source and Target cards
