### ISSUE TITLE
Decklist search doesn't let you choose number of cores

### ISSUE THREAD

**Issue by sacrelicious2** [Alsciende/thronesdb#59]
The decklist searcher (https://thronesdb.com/decklists/search) let's you filter based upon which packs you have, but doesn't let you specify how many core sets you have. This is something that would be rather useful for those with only 1 or 2 cores.

**Comment by Alsciende** [comment]
Sorry, I cannot fix this. Computing the number of cores required for each decklist on the fly is too expensive.
