### ISSUE TITLE
Edit published deck

### ISSUE THREAD

**Issue by Sotiris38** [Alsciende/thronesdb#60]
Hi!

I have published a deck I made in thronesdb and I would like to make a few changes. However, when I try to do that by clicking the "edit" button, the only things I can edit are the name and the description of the deck, not the cards themselves. Is there a way to do that?

Thanks a bunch! Will be waiting to hearing from you guys as soon as possible!

Cheers!

Sotiris

**Comment by Alsciende** [comment]
You can't change a published decklist. You have to change your private deck and publish it again, as another version.
