### ISSUE TITLE
Searching decks with different versions of characters

### ISSUE THREAD

**Issue by Korppi88** [Alsciende/thronesdb#64]
If you are trying to search for decks with the new version of Catelyn Stark (wotn) for example, the search proposes you 2 Catelyn Starks, which both lead to decks with only core set Catelyn. I believe it's the same with all same named characters with different versions.
So maybe adding (core), (wotn) etc. for different versions.

**Comment by mplain** [comment]
Just care here to report this same bug.

The newly released Riverrun made me wonder if people had any success with Tully/Sacrifice decks.

**Comment by Alsciende** [comment]
Closed with https://github.com/Alsciende/thronesdb/commit/0c15f2171ee7e70ee0b99d860a4eaee0391852cc
