### ISSUE TITLE
FAQ + Tournament Regulations

### ISSUE THREAD

**Issue by mplain** [Alsciende/thronesdb#78]
FAQ and Tournament Regulations, marked with html tags. Please add to the site :)

[_HTML.zip](https://github.com/Alsciende/thronesdb/files/428276/_HTML.zip)

**Comment by mplain** [comment]
Any progress with this one? :)

**Comment by mplain** [comment]
Cedric, would you please upload these two files.

I'm referring people to the FAQ all the time when answering rules questions, would be much more convenient to give a direct link to the relevant FAQ entry rather than to the whole PDF document on FFG's website.

Thanks.

**Comment by Alsciende** [comment]
I don't have the time to upload this right now. I'll try to find some time this week, tonight if possible. Hopefully it won't take too long.
