### ISSUE TITLE
deck download is not working. 

### ISSUE THREAD

**Issue by Pagewaiter** [Alsciende/thronesdb#8]
I am using Google Chrome and I can not download my decks. This is the error I get. 

Failed to load resource: net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION
http://thronesdb.com/deck/export/octgn/171:1 

GET http://thronesdb.com/deck/export/octgn/171 net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

**Comment by Pagewaiter** [comment]
it seems to just be on My Decks I have been able to download published decks from other people.

**Comment by Alsciende** [comment]
There must be an issue with that particular deck. Can you paste its content here?

**Comment by Alsciende** [comment]
I'm sorry that I stole your deck and forgot to note your user_id. Here is the content of the o8d file of the deck. If you want you can also give me your username, I'll give you your deck back.
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<deck game="30c200c9-6c98-49a4-a293-106c06295c05" sleeveid="0">
  <section name="Faction" shared="False">
    <card qty="1" id="fd2a37d8-a528-456e-a0de-33846469b1ea">House Martell</card>
  </section>
  <section name="Agenda" shared="False">
    <card qty="1" id="b3fd4493-5ee7-4e46-9b3b-4ea3d767198b">Banner of the Rose</card>
  </section>
  <section name="Plots" shared="False">
    <card qty="1" id="de88edda-f5a4-4985-8ac1-2b8205c13416">A Clash of Kings</card>
    <card qty="1" id="0fb3ad4b-5cf3-49e9-a33f-484ecafeabf8">A Noble Cause</card>
    <card qty="1" id="a02bce64-e292-487e-a666-cd07b4a11e59">A Storm of Swords</card>
    <card qty="1" id="0b94080f-2207-4663-8990-f9370ab77709">Jousting Contest</card>
    <card qty="1" id="fedb6fe6-2f55-4c42-9798-3e091b2b2573">Rebuilding</card>
    <card qty="1" id="a380b0e0-610c-47f9-ac9f-ae12163b45fd">Summons</card>
    <card qty="1" id="d10a1ced-df94-419b-af8e-4eadc2eb4688">Wildfire Assault</card>
  </section>
  <section name="Characters" shared="False">
    <card qty="2" id="499ed82d-cc0e-43a5-89ba-a748b388f528">Littlefinger</card>
    <card qty="2" id="78845c6e-c91a-47a2-9742-d72b19d0ed26">Varys</card>
    <card qty="2" id="7412a0da-c314-4852-ab1f-04bb163dac39">Areo Hotah</card>
    <card qty="2" id="fa34ed25-de84-45c9-89c1-1428ec505458">Arianne Martell</card>
    <card qty="2" id="295184b5-9b32-45d7-a870-c2a5580e1f75">Doran Martell</card>
    <card qty="2" id="b32b7ea7-7997-4b02-8b2f-25ad4d1072fa">Edric Dayne</card>
    <card qty="2" id="af50c8d3-6063-4bbc-a812-e74fa821360e">Obara Sand</card>
    <card qty="2" id="73a43b0f-8337-4e71-96b7-9553d5d57ddf">The Red Viper</card>
    <card qty="2" id="c549499d-6a95-460a-a075-c4592d2f768f">Desert Scavenger</card>
    <card qty="2" id="e0abbec3-188e-4cc1-8a86-5142a47367cd">Greenblood Trader</card>
    <card qty="2" id="7f066373-ab06-4601-943f-3fcd0e7eabf3">House Dayne Knight</card>
    <card qty="2" id="9e0df853-1c6d-4be2-b799-fe69524a6057">Margaery Tyrell</card>
    <card qty="2" id="dfb7512e-0d80-4dff-8fdf-4807d93ba159">The Knight of Flowers</card>
    <card qty="2" id="9236001e-f82d-4a77-ad16-ccd48a7bd1dd">Courtesan of the Rose</card>
    <card qty="2" id="e1278811-db3b-4097-9f7c-54d9bab37f91">Olenna's Informant</card>
  </section>
  <section name="Attachments" shared="False">
    <card qty="2" id="f97ccf1a-5b0d-490f-9968-78330e92171c">Seal of the Hand</card>
    <card qty="3" id="a8bebc54-d01c-424d-8839-460ec09b733f">Milk of the Poppy</card>
    <card qty="2" id="aec7e23f-3e46-49b9-bd6b-37075b3646dd">Syrio's Training</card>
    <card qty="2" id="9e6bf142-159b-4a3b-9d4c-d8bf233a6f0c">Dawn</card>
    <card qty="2" id="4c8a114e-106c-4460-846b-28f73914fc11">Heartsbane</card>
  </section>
  <section name="Events" shared="False">
    <card qty="2" id="c5d78fb6-ff52-4012-ac95-547ed9feec0f">The Hand's Judgment</card>
    <card qty="2" id="427a5213-1be5-4b36-94be-04a5b3486575">Doran's Game</card>
    <card qty="2" id="92d9670d-d842-4c6c-990c-e1e5cb05759d">Growing Strong</card>
    <card qty="2" id="202b37de-c6bf-4c21-93fd-f3cf6bbad04d">"The Bear and the Maiden Fair"</card>
  </section>
  <section name="Locations" shared="False">
    <card qty="2" id="90452d99-6a6f-4d0d-b3a1-bb92e7110d1d">The Kingsroad</card>
    <card qty="2" id="51a3e04f-3f44-4417-8d7c-1f116acd5c80">The Roseroad</card>
    <card qty="2" id="982acc7e-86c0-4bdd-84da-3b05e53dffa1">Ghaston Grey</card>
    <card qty="2" id="f2772a6e-2ed4-4fb9-8699-5497aee496e3">Sunspear</card>
    <card qty="3" id="6b6df968-1810-4e4d-b739-9256caac008b">Blood Orange Grove</card>
  </section>
  <notes><![CDATA[]]></notes>
</deck>
```

**Comment by Pagewaiter** [comment]
Thanks my user name is Mosley.

On Wednesday, August 19, 2015, Alsciende <notifications@github.com> wrote:

> I'm sorry that I stole your deck and forgot to note your user_id. Here is
> the content of the o8d file of the deck. If you want you can also give me
> your username, I'll give you your deck back.
>
> <?xml version="1.0" encoding="utf-8" standalone="yes"?>
> <deck game="30c200c9-6c98-49a4-a293-106c06295c05" sleeveid="0">
>   <section name="Faction" shared="False">
>     <card qty="1" id="fd2a37d8-a528-456e-a0de-33846469b1ea">House Martell</card>
>   </section>
>   <section name="Agenda" shared="False">
>     <card qty="1" id="b3fd4493-5ee7-4e46-9b3b-4ea3d767198b">Banner of the Rose</card>
>   </section>
>   <section name="Plots" shared="False">
>     <card qty="1" id="de88edda-f5a4-4985-8ac1-2b8205c13416">A Clash of Kings</card>
>     <card qty="1" id="0fb3ad4b-5cf3-49e9-a33f-484ecafeabf8">A Noble Cause</card>
>     <card qty="1" id="a02bce64-e292-487e-a666-cd07b4a11e59">A Storm of Swords</card>
>     <card qty="1" id="0b94080f-2207-4663-8990-f9370ab77709">Jousting Contest</card>
>     <card qty="1" id="fedb6fe6-2f55-4c42-9798-3e091b2b2573">Rebuilding</card>
>     <card qty="1" id="a380b0e0-610c-47f9-ac9f-ae12163b45fd">Summons</card>
>     <card qty="1" id="d10a1ced-df94-419b-af8e-4eadc2eb4688">Wildfire Assault</card>
>   </section>
>   <section name="Characters" shared="False">
>     <card qty="2" id="499ed82d-cc0e-43a5-89ba-a748b388f528">Littlefinger</card>
>     <card qty="2" id="78845c6e-c91a-47a2-9742-d72b19d0ed26">Varys</card>
>     <card qty="2" id="7412a0da-c314-4852-ab1f-04bb163dac39">Areo Hotah</card>
>     <card qty="2" id="fa34ed25-de84-45c9-89c1-1428ec505458">Arianne Martell</card>
>     <card qty="2" id="295184b5-9b32-45d7-a870-c2a5580e1f75">Doran Martell</card>
>     <card qty="2" id="b32b7ea7-7997-4b02-8b2f-25ad4d1072fa">Edric Dayne</card>
>     <card qty="2" id="af50c8d3-6063-4bbc-a812-e74fa821360e">Obara Sand</card>
>     <card qty="2" id="73a43b0f-8337-4e71-96b7-9553d5d57ddf">The Red Viper</card>
>     <card qty="2" id="c549499d-6a95-460a-a075-c4592d2f768f">Desert Scavenger</card>
>     <card qty="2" id="e0abbec3-188e-4cc1-8a86-5142a47367cd">Greenblood Trader</card>
>     <card qty="2" id="7f066373-ab06-4601-943f-3fcd0e7eabf3">House Dayne Knight</card>
>     <card qty="2" id="9e0df853-1c6d-4be2-b799-fe69524a6057">Margaery Tyrell</card>
>     <card qty="2" id="dfb7512e-0d80-4dff-8fdf-4807d93ba159">The Knight of Flowers</card>
>     <card qty="2" id="9236001e-f82d-4a77-ad16-ccd48a7bd1dd">Courtesan of the Rose</card>
>     <card qty="2" id="e1278811-db3b-4097-9f7c-54d9bab37f91">Olenna's Informant</card>
>   </section>
>   <section name="Attachments" shared="False">
>     <card qty="2" id="f97ccf1a-5b0d-490f-9968-78330e92171c">Seal of the Hand</card>
>     <card qty="3" id="a8bebc54-d01c-424d-8839-460ec09b733f">Milk of the Poppy</card>
>     <card qty="2" id="aec7e23f-3e46-49b9-bd6b-37075b3646dd">Syrio's Training</card>
>     <card qty="2" id="9e6bf142-159b-4a3b-9d4c-d8bf233a6f0c">Dawn</card>
>     <card qty="2" id="4c8a114e-106c-4460-846b-28f73914fc11">Heartsbane</card>
>   </section>
>   <section name="Events" shared="False">
>     <card qty="2" id="c5d78fb6-ff52-4012-ac95-547ed9feec0f">The Hand's Judgment</card>
>     <card qty="2" id="427a5213-1be5-4b36-94be-04a5b3486575">Doran's Game</card>
>     <card qty="2" id="92d9670d-d842-4c6c-990c-e1e5cb05759d">Growing Strong</card>
>     <card qty="2" id="202b37de-c6bf-4c21-93fd-f3cf6bbad04d">"The Bear and the Maiden Fair"</card>
>   </section>
>   <section name="Locations" shared="False">
>     <card qty="2" id="90452d99-6a6f-4d0d-b3a1-bb92e7110d1d">The Kingsroad</card>
>     <card qty="2" id="51a3e04f-3f44-4417-8d7c-1f116acd5c80">The Roseroad</card>
>     <card qty="2" id="982acc7e-86c0-4bdd-84da-3b05e53dffa1">Ghaston Grey</card>
>     <card qty="2" id="f2772a6e-2ed4-4fb9-8699-5497aee496e3">Sunspear</card>
>     <card qty="3" id="6b6df968-1810-4e4d-b739-9256caac008b">Blood Orange Grove</card>
>   </section>
>   <notes><![CDATA[]]></notes>
> </deck>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Alsciende/thronesdb/issues/8#issuecomment-132516399>.
>


-- 

--
Jason Mosley
Founder of Pagewaiter, LLC
Web Design & Development

web: Pagewaiter.com | twitter: @Mosley | phone: 412.223.7727

**Comment by Alsciende** [comment]
Ok I returned your deck to you.

**Comment by ZeromusPE** [comment]
Deck download doesn't work for me either.  I try downloading to a text file and it just saves an empty file called "txt".
