### ISSUE TITLE
Deck Won't Build or Delete

### ISSUE THREAD

**Issue by MasonTodd** [Alsciende/thronesdb#82]
I tried building a Targaryen No Agenda Deck and it came to a blank screen. I exited and tried to access the deck from my list and it said the deck didn't exist.
I tried to delete it and the message came up saying it had been deleted, but the link to the deck was still there. 
I tried again with other decks, a fealty worked fine, but No Agenda for other factions resulted in the same problems as above.

**Comment by fafranco82** [comment]
Fixed with PR #83

**Comment by MasonTodd** [comment]
I'm sorry, but I am still having the problem.

**Comment by fafranco82** [comment]
It's not merged yet. @Alsciende will close this issue when the fix is merged and up in the server.

**Comment by Alsciende** [comment]
Sorry for the delay, been busy.
