### ISSUE TITLE
Card Name Autocompletion is always in English, doesn't respect the locale

### ISSUE THREAD

**Issue by fatelesscn** [Alsciende/thronesdb#84]
if i use trans ,and type # in comment,there is only en card's name.
![111](https://cloud.githubusercontent.com/assets/16491120/17990091/31557f82-6b65-11e6-9d20-8bfb541c24cc.png)

and this is the right
![23](https://cloud.githubusercontent.com/assets/16491120/17990104/6956fbea-6b65-11e6-8c09-a6affa79d3b6.jpg)

**Comment by Alsciende** [comment]
This is not true. You are seeing English card names for the untranslated cards. Type in "el" for example, and you'll see Spanish card names.
