### ISSUE TITLE
Oops! An Error Occurred The server returned a "405 Method Not Allowed".

### ISSUE THREAD

**Issue by edmundnormal** [Alsciende/thronesdb#89]
'Ey up --

First up - absolutely love ThronesDB.

I'm trying to complete a deck, but I can't for the life of me add new cards and then save them.  When I attempt this, a blank screen appears, and if I refresh I am greeted with the above message.  Any thoughts?

Thanks a mil,

Bettsy

**Comment by Alsciende** [comment]
Hi Bettsy.

We just fixed an issue regarding the saving of decks. Can you please try again?

**Comment by edmundnormal** [comment]
Hi there -

Sorted!  You bloody legends!

Thanks a mil,

Bettsy
