### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by fafranco82** [Alsciende/thronesdb#92]
The SSL Certificate used for HTTPS navigation seems to be only valid for "thronesdb.com". When you change the locale, landing in "es.thronesdb.com", the browser shows a warning message about untrusty certificate.

Is it possible to use a certificate valid to es.thronedb.com (granted to *.thronesdb.com) or use a new certificate por es.thronesdb.com?

I can see that the CA is Let's Encrypt, but I don't know if it is possible update the domain for the certificate or not.

**Comment by itadakimas** [comment]
Let's Encrypt doesn't support wildcard certifiates (see [F.A.Q](https://letsencrypt.org/docs/faq)). I guess they would have to create another certificate for the spanish version of the website. Or maybe use a subdirectory like thronesdb.com/es.

**Comment by Draugrist** [comment]
Wildcards are coming in 2018 https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html

**Comment by stopfstedt** [comment]
old(er) ticket, this has been fixed since.

![selection_159](https://user-images.githubusercontent.com/1410427/47687484-b3576e00-db9d-11e8-9182-f808ed2f1ec5.png)
