### ISSUE TITLE
Cards stay in deck after removing their chapter/exp from Sets

### ISSUE THREAD

**Issue by erictrigo** [Alsciende/thronesdb#98]
If you add a card from a certain pack/exp to your deck, and then unselect that pack/exp from the "Sets" option, the cards remain in the deck. That means that you are unable to get rid of them until you reselect that pack/exp specifically to set the number of copies to zero.

**Comment by Alsciende** [comment]
That's on purpose. And you can remove them: just click on the card and select 0 in the dialog header.
